model_type: 4
input_nc: 3
patch_size: 64

#0 - 24GB, 1 - 16GB, 2 - 10 - 12GB, 3 - 8GB
batch_size: [256, 64, 48, 16] #amount of images to accumulate before backprop
load_size: [256, 64, 48, 16] #amount of images to load in GPU. load_size <= batch_size

num_blocks: 6
weight_decay: 0.0
dropout_rate: 0.0
augment_key: ["none"]

g_lr: 0.0002
d_lr: 0.0005
min_epochs: 200
max_epochs: 200

dataset_version: "div2k"
low_path: "/dpsr_x4/*.png"
high_path: "/bicubic_x4/*.png"
dataset_repeats: 500