model_type: 1
input_nc: 3
patch_size: 64

#0 - 32GB, 1 - 24GB, 1 - 16GB, 2 - 10 - 12GB, 3 - 8GB
batch_size: [1972, 1536, 256, 1024, 256] #amount of images to accumulate before backprop
load_size: [896, 768, 128, 512, 128] #amount of images to load in GPU. load_size <= batch_size

num_blocks: 6

min_epochs: 200
max_epochs: 200

dataset_version: "sr-hypersim"
low_path: "/classic_x4/*.png"
high_path: "/high/*.png"