model_type: 4
input_nc: 3
patch_size: 64

#0 - 24GB, 1 - 16GB, 2 - 10 - 12GB, 3 - 8GB
batch_size: [512, 512, 392, 32] #amount of images to accumulate before backprop
load_size: [256, 256, 196, 32] #amount of images to load in GPU. load_size <= batch_size

num_blocks: 3

min_epochs: 400
max_epochs: 400

dataset_version: "div2k"
low_path: "/lr/*.png"
high_path: "/bicubic_x4/*.png"