model_type: 1
input_nc: 3
patch_size: 64
num_blocks: 6

#0 - 24GB, 1 - 16GB, 2 - 10 - 12GB, 3 - 8GB
batch_size: [1536, 256, 1024, 256] #amount of images to accumulate before backprop
load_size: [768, 128, 512, 128] #amount of images to load in GPU. load_size <= batch_size

min_epochs: 400
max_epochs: 400

dataset_version: "CityScapes_GAN"
img_path: "/train/*.jpg"
mask_path: ""