model_type: 1
input_nc: 3
#patch_size: 64
patch_size: 256
num_blocks: 6

#0 - 24GB, 1 - 16GB, 2 - 10 - 12GB, 3 - 8GB
#batch_size: [4096, 2048, 2048, 256] #amount of images to accumulate before backprop
#load_size: [2048, 1024, 1024, 128] #amount of images to load in GPU. load_size <= batch_size
batch_size: [128, 128, 2048, 256] #amount of images to accumulate before backprop
load_size: [64, 64, 1024, 128] #amount of images to load in GPU. load_size <= batch_size

min_epochs: 100
max_epochs: 100

dataset_version: "CityScapes"
img_path_train: "/leftImg8bit/train/*/*.png"
mask_path_train: "/gtFine/train/*/*_color.png"

img_path_test: "/leftImg8bit/val/*/*.png"
mask_path_test: "/gtFine/val/*/*_color.png"
