model_type: 1
input_nc: 3
patch_size: 64
num_blocks: 6

#0 - 24GB, 1 - 16GB, 2 - 10 - 12GB, 3 - 8GB
batch_size: [384, 2048, 2048, 256] #amount of images to accumulate before backprop
load_size: [192, 1024, 1024, 128] #amount of images to load in GPU. load_size <= batch_size

min_epochs: 100
max_epochs: 100

dataset_a_train: "Segmentation Dataset/FCG-Synth-01-patched/train-rgb/sequence.0/*.png"
dataset_b_train: "Segmentation Dataset/CityScapes-patched/train-rgb/*/*.png"

dataset_a_test: "Segmentation Dataset/FCG-Synth-01/sequence.0/*.camera.png"
dataset_b_test: "Segmentation Dataset/CityScapes/leftImg8bit/train/*/*.png"
